FROM python:3.11-alpine

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt
COPY *.py /code/

RUN pip install psycopg2-binary
RUN pip install -r /code/requirements.txt


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]