version: "3.1"

# Default Configuration
# Server : <container_name>
# Username : postgres
# Password : <POSTGRES_PASSWORD>
# Database : <empty>

services:
    db:
        container_name: postgres-container
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080